### ISSUE TITLE
Error in config/nonprofit-cloud.json

### ISSUE THREAD

**Issue by programmer2coder** [acrosman/Salesforce-NpcEdu-Scratch#1]
I got this error is in trying to create a Scratch Org using config/nonprofit-cloud.json:

ERROR running force:org:create:  All JSON input must have heads down camelcase keys.  
E.g., { sfdcLoginUrl: "https://login.salesforce.com" }
Found "IndustriesSettings" in
{
    "orgName": "Nonprofit Cloud Example",
    "edition": "Developer",
    etc.

**Comment by acrosman** [comment]
Thanks for pointing it out @programmer2coder.  Fixed.
