### ISSUE TITLE
Suggestion NPC update

### ISSUE THREAD

**Issue by jkenzer** [acrosman/Salesforce-NpcEdu-Scratch#8]
Just a suggestion. You may want to add the `"enableGroupMembershipPref": true ` in industriesSettings. This seems to be the model that the docs rely on when creating household relationships. I think that you would also need to include the feature "ContactsToMultipleAccounts".

Also, thanks a ton for this template. Saved me a bunch of time. Super appreciate it!

**Comment by acrosman** [comment]
Thanks for the suggestions. It's good to hear it was helpful.
